inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-discourse: default.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.7
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    # - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  Rails:
    enabled: true

AsciiComments:
  Enabled: false

CyclomaticComplexity:
  Max: 8

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 35

Metrics/MethodLength:
  Max: 22

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/password_resets_controller.rb'

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/sessions_helper.rb'

Rails/OutputSafety:
  Enabled: false