version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: otasuke_app_development
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: always
volumes:
  mysql-data:
    driver: local